# prompt.zsh — Powerlevel10k setup
#
# The instant-prompt block MUST stay at the top of this file.
# It runs before everything else to render the previous shell's prompt
# instantly while the rest of the config loads in the background.

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Powerlevel10k theme
source "$HOME/.zsh/themes/powerlevel10k/powerlevel10k.zsh-theme"

# Source user-specific p10k configuration if it exists
# (generated by `p10k configure` — bootstrap.sh runs the wizard on first install)
[[ ! -f "$HOME/.p10k.zsh" ]] || source "$HOME/.p10k.zsh"
